services:
  mariadb:
    image: mariadb:latest
    container_name: to_do_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - "3306:3306"
