name: SonarQube analysis

on:
  push:
    branches:
      - main
      - '113239-Pedro-Feature'   # ou usa 'feature/*' para cobrir vÃ¡rios
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: read # permite ao SonarQube decorar PRs com resultados

jobs:
  Analysis:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk # ðŸ”¹ executa tudo com Java 17

    steps:
      # 1ï¸âƒ£ Clonar o repositÃ³rio
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # importante para o Sonar comparar branches

      # 2ï¸âƒ£ Executar a anÃ¡lise SonarQube
      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # necessÃ¡rio para PRs
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # token criado no SonarQube
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # URL do teu SonarQube (ex: https://sonarqube.mycompany.com)
        with:
          args: >
            -Dsonar.projectKey=LEI-122123_Semana-3-TO-DO
